//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metric
    {
        public Metric()
        {
            this.UserWorkouts = new HashSet<UserWorkout>();
        }
    
        public int MetricID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UnitOfMeasurement { get; set; }
        public Nullable<int> TargetCalories { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<UserWorkout> UserWorkouts { get; set; }
    }
}
