//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWorkout
    {
        public int UserWorkoutID { get; set; }
        public Nullable<int> MetricID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> UserWorkout1 { get; set; }
        public Nullable<int> CaloriesBurnt { get; set; }
        public Nullable<System.DateTime> WorkoutDate { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Metric Metric { get; set; }
        public virtual User User { get; set; }
    }
}
